Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_1.py
g1='"hi mom",i said. "how are you/"'
g1
'"hi mom",i said. "how are you/"'
'"hi mom",i said. "how are you/"'g1='"hi mom",i said. "how are you/"'
SyntaxError: invalid syntax
g2='"hi mom",i said. '"how are you/"
g2
'"hi mom",i said. how are you/'
g2='"hi mom",i said. '"how are you"
g2
'"hi mom",i said. how are you'
g3='"hi mom",i said. '"how are you"'
SyntaxError: incomplete input

= RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_1.py
\\\\
\
\
\

good bye

hjgvhjejh
KeyboardInterrupt

'abc' 
KeyboardInterrupt
'abc' 'def'
'abcdef'
'abc' + 'def'
'abcdef'
s2='abc '*4
print(s2)
abc abc abc abc 

====================================== RESTART: Shell =====================================
z=2
z=z**2**3
print(x)
Traceback (most recent call last):
  File "<pyshell#16>", line 1, in <module>
    print(x)
NameError: name 'x' is not defined
print(z)
256
x=6

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_1.py =====
256
-8

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_1.py =====
256
-8

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_2.py =====
hello world
values of x is 8 valus of y is 10
s1="""This is a multi-line string"""
s1
'This is a multi-line string'
print(s1)
This is a multi-line string

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_4.py =====
Traceback (most recent call last):
  File "C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_4.py", line 1, in <module>
    print('\\',*4)
TypeError: Value after * must be an iterable, not int

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_4.py =====
Traceback (most recent call last):
  File "C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_4.py", line 1, in <module>
    print('\\',*4)
TypeError: Value after * must be an iterable, not int

print('\\',*4)
print('\\\n'*3)
print('good bye')
KeyboardInterrupt
print('\\',*4)
print('\\\n'*3)
print('good bye')
SyntaxError: multiple statements found while compiling a single statement
print('\\',*4)
Traceback (most recent call last):
  File "<pyshell#23>", line 1, in <module>
    print('\\',*4)
TypeError: Value after * must be an iterable, not int
print('\\',*4)
print('\\\n'*3)
print('good bye')
KeyboardInterrupt
print('\\'*4)
\\\\
print('\\\n'*4)
\
\
\
\

H="STAY\t\nWITH\t\nCONSISTENCY\t\nEVERYTIME"
PRINT(H)
Traceback (most recent call last):
  File "<pyshell#27>", line 1, in <module>
    PRINT(H)
NameError: name 'PRINT' is not defined
print(H)
STAY	
WITH	
CONSISTENCY	
EVERYTIME
a=apple
Traceback (most recent call last):
  File "<pyshell#29>", line 1, in <module>
    a=apple
NameError: name 'apple' is not defined. Did you mean: 'tuple'?
a=apple
Traceback (most recent call last):
  File "<pyshell#30>", line 1, in <module>
    a=apple
NameError: name 'apple' is not defined. Did you mean: 'tuple'?
KeyboardInterrupt
a='apple'
a.split()
['apple']
z='jango'
z.split()
['jango']
z.sorted()
Traceback (most recent call last):
  File "<pyshell#35>", line 1, in <module>
    z.sorted()
AttributeError: 'str' object has no attribute 'sorted'
split(z)
Traceback (most recent call last):
  File "<pyshell#36>", line 1, in <module>
    split(z)
NameError: name 'split' is not defined
sorted(z)
['a', 'g', 'j', 'n', 'o']

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_4.py =====
enter your string:ganesh gangli
Traceback (most recent call last):
  File "C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_4.py", line 6, in <module>
    anagram(g1,g1)
NameError: name 'g1' is not defined

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_4.py =====
enter your string:ganesh gangli
Traceback (most recent call last):
  File "C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_4.py", line 6, in <module>
    anagram(g1,g2)
NameError: name 'g1' is not defined

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_4.py =====
enter your string:ganguly
Traceback (most recent call last):
  File "C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_4.py", line 6, in <module>
    print(anagram(inp[0],inp[1]))
IndexError: list index out of range

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_4.py =====
enter your string:ganesh
Traceback (most recent call last):
  File "C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_4.py", line 6, in <module>
    print(anagram(inp[0],inp[1]))
IndexError: list index out of range

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_4.py =====
enter your string:gangully ganesh
no

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_6.py =====
ball
no

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_6.py =====
madam
yes

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_7.py =====
hai janu hwllo
Traceback (most recent call last):
  File "C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_7.py", line 9, in <module>
    a=extract_vowel(inp)
NameError: name 'extract_vowel' is not defined

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_7.py =====
hai janu
vowels: 

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_7.py =====
hai jahnavi
i= h
i= a
i: a temp_vowel: 
i= i
i: i temp_vowel: 
i=  
i= j
i= a
i: a temp_vowel: 
i= h
i= n
i= a
i: a temp_vowel: 
i= v
i= i
i: i temp_vowel: 
vowels: 

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_8.py =====
hai arkun
i= h
i: h temp_vowel: 
i= a
i= i
i=  
i= a
i= r
i: r temp_vowel: 
i= k
i= u
i= n
i: n temp_vowel: 
Traceback (most recent call last):
  File "C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_8.py", line 9, in <module>
    a=extract_consoants(inp)
  File "C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_8.py", line 7, in extract_consoants
    return temp_consoant
NameError: name 'temp_consoant' is not defined

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_8.py =====
hai arun
Traceback (most recent call last):
  File "C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_8.py", line 9, in <module>
    a=temp_consoant(inp)
NameError: name 'temp_consoant' is not defined

====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_8.py =====
enter:hai varun kumar nice Work ra annaya737867787843*&&^&$%^%*%%^$^&
vowles: 
vowel count: 13 

 consnants: hrnkmrncrkrnny 
consnants count: 

 number are: 737867787843 
special characters: 24
>>> 
====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_8.py =====
enter:hai ra mawa ela gunav %^^$%^$antha mandheee
vowles: aiaaaeauaaaaeee 
vowel count: 15 

 consnants: hrmwlgnnthmndh 
consnants count: 15 

 number are:  count of digits 0 
 special:     v %^^$%^$  
special characters: 14
>>> 
====== RESTART: C:/Users/User/Desktop/python practice _2721113/day_5/day5_output_8.py =====
enter:hai ra mawa nice work keepit up6778878778464 $^&%&^$%^&^^&%&* hahhahahhah
vowles: aiaaaieoeeiuaaaa 
vowel count: 16 

 consnants: hrmwncwrkkptphhhhhhh 
consnants count: 16 

 number are: 6778878778464 count of digits 13 
 special:        $^&%&^$%^&^^&%&*  
special characters: 24
